title: Ivan

description: >- 
  Ex Nihilo Nihil Fit

baseurl: ""
url: "https://orange-my-cat.github.io/"

github_username:  orange-my-cat
linkedin_username: ivanpeh

google_analytics: "UA-224679057-1"

exclude:
- README.md
- LICENSE

plugins:
- jekyll-seo-tag