baseURL = 'https://orange-my-cat.github.io/'
languageCode = 'en-us'
title = 'Ivan:high_brightness:'
googleAnalytics = 'G-4T0TFTB785'

[Params]
  seotitle = 'Ivan'
  description = 'Data Science & Mathematics Student'
  enableEmoji = 'true'
  image = 'feature-image.jpg'