baseURL = 'https://orange-my-cat.github.io/'
languageCode = 'en-us'
title = 'Ivan'
googleAnalytics = 'G-4T0TFTB785'

[Params]
  seotitle = 'seotitle'
  description = 'description'
  enableEmoji = 'true'