baseURL = "https://orange-my-cat.github.io/"
languageCode = "en-us"
title = "Ivan"
googleAnalytics = "G-4T0TFTB785"
pluralizelisttitles = false

[Params]
  longTitle = "Ivan - Data Science & Maths Student at UWA"
  description = "A driven, results-oriented student at UWA with a background in data science, mathematics, and statistics. I've also had experience in software and web development."
  image = "seo_image.png"
  facebook = "https://www.facebook.com/peh.wv"
  instagram = "https://www.instagram.com/ivan.pwv/"
  linkedin = "https://www.linkedin.com/in/ivanpeh/"
  github = "https://github.com/orange-my-cat"
