name = "custom"
license = "MIT"
licenselink = "https://github.com/orange-my-cat/orange-my-cat.github.io/blob/main/themes/custom/LICENSE"
description = "custom theme for my personal site"
homepage = "https://orange-my-cat.github.io/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "ivan"
  homepage = "https://orange-my-cat.github.io/"

[original]
  name = ""
  homepage = ""
  repo = ""
